version: '3'
services:
  workspace:
    image: seasketch/geoprocessing-workspace
    # These env vars make it easy to connect to the database service
    # Use `psql` without arguments to connect from within the workspace
    # environment:
    #   PGHOST: "db"
    #   PGUSER: "docker"
    #   PGPASSWORD: "docker"
    #   PGDATABASE: "gis"
    # VSCode will clone repo into a named volume automatically

    # Named volums of targeted paths for faster disk performance
    volumes:
      - ..:/workspaces/geoprocessing:cached
      - test_volume:/workspaces/geoprocessing/scripts/init/__test__
      - root_nm_volume:/workspaces/geoprocessing/node_modules
      - gp_nm_volume:/workspaces/geoprocessing/packages/geoprocessing/node_modules
      - toe_nm_volume:/workspaces/geoprocessing/packages/template-ocean-eez/node_modules
      - tbp__nm_volume:/workspaces/geoprocessing/packages/template-blank-project/node_modules
      

    # network_mode: service:db
    command: sleep infinity
    user: root
  # db:
  #   image: seasketch/geoprocessing-db
  #   # Port 54320 will be exposed on the host machine. For example, with
  #   # QGIS installed you can connect to the database on this port. Use
  #   # the username, password, and database name listed below.
  #   # If working on more than one project at a time you may want to change the 
  #   # exposed port number to avoid conflicts
  #   ports:
  #     - "54320:5432"

volumes:
  test_volume:
  root_nm_volume:
  gp_nm_volume:
  toe_nm_volume:
  tbp__nm_volume:

