version: '3'
services:
  db:
    image: seasketch/gp-data-db
    # Port 54320 will be exposed on the host machine. For example, with
    # QGIS installed you can connect to the database on this port. Use
    # the username, password, and database name listed below.
    # If working on more than one project at a time you may want to change the 
    # exposed port number to avoid conflicts
    ports:
      - "54320:5432"
  workspace:
    image: seasketch/gp-data-workspace
    # These env vars make it easy to connect to the database service
    # Use `psql` without arguments to connect from within the workspace
    environment:
      PGHOST: "db"
      PGUSER: "docker"
      PGPASSWORD: "docker"
      PGDATABASE: "gis"
    # The contents of the project directory in the host will be mirrored
    # within the workspace. 
    volumes:
      - $HOME/.aws/credentials:/root/.aws/credentials:ro
    # Switch to the data directory on startup
    working_dir: /project/data
    command: ["bash"]