#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npx lerna run prepare # transpiles core geoprocessing code for templates
# run tests including e2e tests not run by Github CI (GDAL, etc.)
# npx lerna run test:node
# npx lerna run test:browser
# npx lerna run test:e2e
