name: CI

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Upgrade npm
        run: npm install -g npm@latest
      - name: Install modules
        run: npm install
      - name: Run tests
        run: npm test
      - name: Create example
        run: npm run create_example && npm install && cd packages/example-project
      - name: Test example
        run: npm test
      - name: Build example
        run: npm run build
        
