name: "Publish Docs"

on:
  push:
    branches:    
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Check node version
        run: node -v
      - name: Upgrade npm
        run: npm install -g npm@8.5
      - name: Check npm version
        run: npm -v
      - name: Install modules
        run: npm install
      - name: Build docs
        run: npm run build-docs 
      - name: Deploy docs 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: packages/geoprocessing/docs