name: Publish wiki docs

# Only publish docs on push to main, which should be done on release
on:
  push:
    branches:    
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Upload Documentation to Wiki
        uses: seasketch/github-wiki-publish-action@v3
        with:
          path: packages/wiki-docs/
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}